#日志测试
logging:
  #级别
  level:
    #开发包 debug
    com.study: debug
    #依赖包 info
    root: INFO
  #文件名
  file:
    name: spring.log
    path: ./logs/
  #切割设置
  logback:
    rollingpolicy:
      #文件格式
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log
      #重启是否删除过期日志
      clean-history-on-start: true
      #文件大小  30M。请修改
      max-file-size: 30720KB
      #日志总大小
      total-size-cap: 0
      #保留天数
      max-history: 7